module.exports = {
  arrowParens: "always",
  bracketSameLine: true,
  bracketSpacing: true,
  htmlWhitespaceSensitivity: "css",
  printWidth: 100,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  useTabs: false,
};

// "arrowParens": "always",
// "bracketSpacing": true,
// "endOfLine": "lf",
// "htmlWhitespaceSensitivity": "css",
// "insertPragma": false,
// "jsxBracketSameLine": false,
// "jsxSingleQuote": false,
// "printWidth": 80,
// "proseWrap": "preserve",
// "quoteProps": "as-needed",
// "requirePragma": false,
// "semi": true,
// "singleQuote": false,
// "tabWidth": 2,
// "trailingComma": "es5",
// "useTabs": false,
// "vueIndentScriptAndStyle": false,
// "parser": "typescript"
